outdir: runs/temporal_analysis

base:
  Nx: 100
  Ny: 100
  steps: 50000
  dt: 0.01
  dx: 1.0
  save_every: 200
  stopping_threshold: 0.0
  min_steps: 50000  # Avoid early stopping

  init_mode: activator_random_spikes
  activator_type: juxtacrine
  nucleation_rate: 0.001
  noise_amplitude: 0.0
  n_points: 10

  act_decay_rate: 1.0
  act_half_sat: 1.0
  inh_half_sat: 1.0
  basal_prod: 0.0

  act_hill_coeff: 3
  inh_hill_coeff: 3

  act_prod_rate: 5.0
  inh_prod_rate: 12.0
  inh_decay_rate: 0.5
  inh_diffusion: 10.0
  act_diffusion: 1.0

  # Additional video and termination plots toggle for batch_runner
  # Turn off to save time if doing large batches
  video_enable: true
  term_plots_enable: true

mode: grid
sweeps:
  set_peak_height: [5, 10, 15, 20]