outdir: runs/collect_metrics

base:
  Nx: 100
  Ny: 100
  steps: 50000
  dt: 0.01
  dx: 1.0
  save_every: 100
  stopping_threshold: 1.0e-3
  min_steps: 10000

  init_mode: random_uniform_over0
  activator_type: juxtacrine
  nucleation_rate: 0.0
  noise_amplitude: 0.0

  act_half_sat: 1.0
  inh_half_sat: 1.0
  basal_prod: 0.0

  act_hill_coeff: 3
  inh_hill_coeff: 3

  act_prod_rate: 5.0
  # inh_prod_rate: 25
  inh_decay_rate: 0.5
  act_decay_rate: 1.0

  # act_diffusion: 1.0
  inh_diffusion: 10.0

  # Additional video and termination plots toggle for batch_runner
  # Turn off to save time if doing large batches
  video_enable: false
  early_enable: false  # For slower videos of initial pattern evolution
  # early_seconds: 0.25
  term_plots_enable: false

  spike_value: 1.0

mode: grid
sweeps:
    inh_prod_rate:  [8, 9, 10, 11, 12, 13]