import os
import numpy as np
import pandas as pd
from pathlib import Path

def analyze_batch_outputs(output_dir: str):
    """
    Loops through the generated batch folder, extracts the safe NPZ arrays,
    and classifies regimes while protecting against floating-point noise.
    """
    path = Path(output_dir)
    npz_files = sorted(path.glob("field_*.npz"))
    
    results = []
    
    for npz_path in npz_files:
        # Load the saved file containing our empty arrays or actual metrics
        data = np.load(npz_path)
        
        A_final = data["A_final"]
        
       
        # Calculate standard deviation to catch completely uniform fields (ON/OFF)
        grid_std = np.std(A_final)
        
        # Pull our safeguarded arrays (Safely an empty array now instead of None!)
        act_max_change = data["act_max_change"]
        
        # --- REGIME CLASSIFICATION LOGIC ---
        if grid_std < 1e-6:
            # If the field is flat, it's either an ON or OFF uniform state
            mean_val = np.mean(A_final)
            if mean_val > 1.0: 
                regime = "ON"
            else:
                regime = "OFF"
                
            # Guard spectral metrics: set to NaN to avoid picking up floating-point noise
            peak_wavelength = np.nan
            peak_sharpness = np.nan
        else:
            # It's a real pattern -> Run normal spectral calculations
            regime = "PATTERNED" 
            peak_wavelength = 12.5 # Placeholder example for downstream metrics
            peak_sharpness = 2.4   # Placeholder example for downstream metrics

        results.append({
            "file": npz_path.name,
            "regime": regime,
            "grid_std": grid_std,
            "has_termination_data": len(act_max_change) > 0
        })
        
    # Convert summarized metrics to a clean DataFrame
    df = pd.DataFrame(results)
    print("\n--- Integrated Batch Classification Results ---")
    print(df.to_string(index=False))
    return df

if __name__ == "__main__":
    # Points to the new temporal analysis outputs generated by the batch runner
    output_folder = "runs/temporal_analysis"
    analyze_batch_outputs(output_folder)